export const GREEN = '#4CAF50';
export const YELLOW = '#FFC107';
export const DARK_GREEN = '#2E7D32';
export const DARK_YELLOW = '#FFA000';

export const lightTheme = {
  background: '#FFFFFF',
  card: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#666666',
  textMuted: '#999999',
  border: '#F2F2F2',
  borderLight: '#E8E8E8',
  primary: GREEN,
  primaryLight: '#E6F5EE',
  accent: YELLOW,
  accentLight: '#FFF8E0',
  success: '#4CAF50',
  warning: '#FFC107',
  danger: '#F44336',
  cardBackground: '#FFFFFF',
  inputBackground: '#F5F5F5',
  placeholder: '#AAAAAA',
  headerBackground: '#FFFFFF',
  tabBarBackground: '#FFFFFF',
  statusBarStyle: 'dark-content',
  statusBarBg: '#FFFFFF',
  green: GREEN,
  yellow: YELLOW,
  toggleBg: '#EBEBEB',
  toggleInactive: '#777777',
  noteBg: '#FFFBE6',
  noteText: '#7A6000',
  timeBadgeBg: '#FFFFFF',
  seatBadgeBg: '#FFF8E0',
  seatText: '#B8860B',
  emptyCardBg: GREEN,
  shadowColor: '#000000',
};

export const darkTheme = {
  background: '#121212',
  card: '#1E1E1E',
  text: '#FFFFFF',
  textSecondary: '#B0B0B0',
  textMuted: '#808080',
  border: '#2C2C2C',
  borderLight: '#3C3C3C',
  primary: DARK_GREEN,
  primaryLight: '#1E3A2A',
  accent: DARK_YELLOW,
  accentLight: '#3A2E1E',
  success: '#2E7D32',
  warning: '#FFA000',
  danger: '#D32F2F',
  cardBackground: '#1E1E1E',
  inputBackground: '#2C2C2C',
  placeholder: '#666666',
  headerBackground: '#1E1E1E',
  tabBarBackground: '#1E1E1E',
  statusBarStyle: 'light-content',
  statusBarBg: '#121212',
  green: DARK_GREEN,
  yellow: DARK_YELLOW,
  toggleBg: '#2C2C2C',
  toggleInactive: '#808080',
  noteBg: '#3A2E1E',
  noteText: '#FFD700',
  timeBadgeBg: '#2C2C2C',
  seatBadgeBg: '#3A2E1E',
  seatText: '#FFD700',
  emptyCardBg: DARK_GREEN,
  shadowColor: '#FFFFFF',
};